In [116]:
import numpy as np
import pandas as pd
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score,f1_score

In [117]:
#Read the data
df=pd.read_csv(r'E:\SEM 4\AML\PROJECT\DATASET\archive (4)\fake_or_real_news.csv')

#Get shape and head
df.shape
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  6335 non-null   int64 
 1   title       6335 non-null   object
 2   text        6335 non-null   object
 3   label       6335 non-null   object
dtypes: int64(1), object(3)
memory usage: 198.1+ KB


In [119]:
df.label.value_counts()

REAL    3171
FAKE    3164
Name: label, dtype: int64

In [120]:
df.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [121]:
#DataFlair - Get the labels
labels=df.label
labels.head()

0    FAKE
1    FAKE
2    REAL
3    FAKE
4    REAL
Name: label, dtype: object

In [122]:
df1 = df['title'] +"\n"+ df['text']
df1

0       You Can Smell Hillary’s Fear\nDaniel Greenfiel...
1       Watch The Exact Moment Paul Ryan Committed Pol...
2       Kerry to go to Paris in gesture of sympathy\nU...
3       Bernie supporters on Twitter erupt in anger ag...
4       The Battle of New York: Why This Primary Matte...
                              ...                        
6330    State Department says it can't find emails fro...
6331    The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332    Anti-Trump Protesters Are Tools of the Oligarc...
6333    In Ethiopia, Obama seeks progress on peace, se...
6334    Jeb Bush Is Suddenly Attacking Trump. Here's W...
Length: 6335, dtype: object

In [123]:
x_train,x_test,y_train,y_test=train_test_split(df['text'], labels, test_size=0.2, random_state=7)

In [126]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df =0.9)
tfidf_train = tfidf_vectorizer.fit_transform(x_train)
tfidf_test = tfidf_vectorizer.transform(x_test)
tfidf_train

<5068x61651 sparse matrix of type '<class 'numpy.float64'>'
	with 1337098 stored elements in Compressed Sparse Row format>

In [127]:
pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train,y_train)
y_pred=pac.predict(tfidf_test)
acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred, pos_label="FAKE")
recall = recall_score(y_test,y_pred,pos_label="FAKE")
f1 = f1_score(y_test,y_pred,pos_label="FAKE")

In [128]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=['FAKE','REAL']))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[588  50]
 [ 42 587]]
Accuracy : 92.74%
Precision : 93.33%
Recall : 92.16%
f1_score : 92.74%


In [129]:
#DECISION TREE
from sklearn.tree import DecisionTreeClassifier
Dt = DecisionTreeClassifier(criterion = 'entropy')
Dt.fit(tfidf_train,y_train)
y_pred = Dt.predict(tfidf_test)
acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred, pos_label="FAKE")
recall = recall_score(y_test,y_pred,pos_label="FAKE")
f1 = f1_score(y_test,y_pred,pos_label="FAKE")

In [130]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=['FAKE','REAL']))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[523 115]
 [117 512]]
Accuracy : 81.69%
Precision : 81.72%
Recall : 81.97%
f1_score : 81.85%


In [131]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(tfidf_train,y_train)
y_pred = knn.predict(tfidf_test)
acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred, pos_label="FAKE")
recall = recall_score(y_test,y_pred,pos_label="FAKE")
f1 = f1_score(y_test,y_pred,pos_label="FAKE")

In [132]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=['FAKE','REAL']))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[638   0]
 [567  62]]
Accuracy : 55.25%
Precision : 52.95%
Recall : 100.0%
f1_score : 69.23%


In [133]:
#LOGISTIC REGRESSION
from sklearn import linear_model
logr = linear_model.LogisticRegression()
logr.fit(tfidf_train,y_train)
y_pred = logr.predict(tfidf_test)
acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred, pos_label="FAKE")
recall = recall_score(y_test,y_pred,pos_label="FAKE")
f1 = f1_score(y_test,y_pred,pos_label="FAKE")

In [134]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=['FAKE','REAL']))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[600  38]
 [ 67 562]]
Accuracy : 91.71%
Precision : 89.96%
Recall : 94.04%
f1_score : 91.95%


In [135]:
#NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(tfidf_train.toarray(),y_train)
y_pred = gnb.predict(tfidf_test.toarray())
acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred, pos_label="FAKE")
recall = recall_score(y_test,y_pred,pos_label="FAKE")
f1 = f1_score(y_test,y_pred,pos_label="FAKE")

In [136]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=['FAKE','REAL']))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[512 126]
 [103 526]]
Accuracy : 81.93%
Precision : 83.25%
Recall : 80.25%
f1_score : 81.72%


In [137]:
#RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(tfidf_train,y_train)
y_pred = rf.predict(tfidf_test)
acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred, pos_label="FAKE")
recall = recall_score(y_test,y_pred,pos_label="FAKE")
f1 = f1_score(y_test,y_pred,pos_label="FAKE")

In [138]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=['FAKE','REAL']))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[584  54]
 [ 55 574]]
Accuracy : 91.4%
Precision : 91.39%
Recall : 91.54%
f1_score : 91.46%


In [139]:
#SUPPORT VECTOR MACHINE
from sklearn import svm
svmc = svm.SVC()
svmc.fit(tfidf_train,y_train)
y_pred = svmc.predict(tfidf_test)
acc_score=accuracy_score(y_test,y_pred)
pre_score = precision_score(y_test,y_pred, pos_label="FAKE")
recall = recall_score(y_test,y_pred,pos_label="FAKE")
f1 = f1_score(y_test,y_pred,pos_label="FAKE")

In [140]:
print("Confusion matrix : \n",confusion_matrix(y_test,y_pred, labels=['FAKE','REAL']))
print(f'Accuracy : {round(acc_score*100,2)}%')
print(f'Precision : {round((pre_score)*100,2)}%')
print(f'Recall : {round((recall)*100,2)}%')
print(f'f1_score : {round((f1)*100,2)}%')

Confusion matrix : 
 [[605  33]
 [ 57 572]]
Accuracy : 92.9%
Precision : 91.39%
Recall : 94.83%
f1_score : 93.08%
